#spring: 
#  datasource: 
#    url:  jdbc:mysql://localhost:3308/multas
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQL55Dialect
#        
#        
#        
